import type { ShadowCase } from './types'

const B = '/api/admin/component-center/advanced-table'
const W = ['updated_at']

export const cases: ShadowCase[] = [
  { name: '统计', path: `${B}/stats`, auth: true },
  { name: '列表 默认', path: `${B}/rows`, auth: true },
  { name: '列表 分页', path: `${B}/rows?page=2&per_page=2`, auth: true },
  { name: '列表 超出页', path: `${B}/rows?page=99`, auth: true },
  { name: '列表 search', path: `${B}/rows?search=%E4%BC%9A%E5%91%98`, auth: true },
  { name: '列表 search tags', path: `${B}/rows?search=a/b`, auth: true },
  { name: '列表 status/category', path: `${B}/rows?status=archived&category=user`, auth: true },
  { name: '列表 owner', path: `${B}/rows?owner=%E6%9D%8E`, auth: true },
  { name: '列表 is_active=false', path: `${B}/rows?is_active=false`, auth: true },
  { name: '列表 is_active=是', path: `${B}/rows?is_active=%E6%98%AF`, auth: true },
  { name: '列表 is_active 未知值', path: `${B}/rows?is_active=maybe`, auth: true },
  { name: '列表 pinned_only', path: `${B}/rows?pinned_only=on`, auth: true },
  { name: '列表 按 score 降序', path: `${B}/rows?sort_field=score&sort_order=DESC`, auth: true },
  { name: '列表 按 due_date', path: `${B}/rows?sort_field=due_date`, auth: true },
  { name: '列表 按 updated_at 降序', path: `${B}/rows?sort_field=updated_at&sort_order=desc`, auth: true },
  { name: '列表 非法排序字段', path: `${B}/rows?sort_field=name&sort_order=x`, auth: true },
  // 新建校验
  { name: '新建 缺名称', method: 'POST', path: `${B}/rows`, body: { row_code: 'x' }, auth: true },
  { name: '新建 缺编码', method: 'POST', path: `${B}/rows`, body: { name: 'x' }, auth: true },
  { name: '新建 编码重复', method: 'POST', path: `${B}/rows`, body: { name: 'x', row_code: 'ADV-001' }, auth: true },
  { name: '新建 状态非法', method: 'POST', path: `${B}/rows`, body: { name: 'x', row_code: '__shadow_r5__', status: 'bogus' }, auth: true },
  {
    name: '新建 状态非法且排序越界（状态先报）',
    method: 'POST',
    path: `${B}/rows`,
    body: { name: 'x', row_code: '__shadow_r5__', status: 'bogus', sort_order: 99999999999 },
    auth: true,
  },
  { name: '新建 排序越界', method: 'POST', path: `${B}/rows`, body: { name: 'x', row_code: '__shadow_r5__', sort_order: '-2147483649' }, auth: true },
  // 编辑
  { name: '编辑 不存在', method: 'PUT', path: `${B}/rows/99999999`, body: {}, auth: true },
  { name: '编辑 名称清空', method: 'PUT', path: `${B}/rows/2`, body: { name: '' }, auth: true },
  { name: '编辑 编码清空', method: 'PUT', path: `${B}/rows/2`, body: { row_code: ' ' }, auth: true },
  { name: '编辑 编码重复', method: 'PUT', path: `${B}/rows/2`, body: { row_code: 'ADV-001' }, auth: true },
  { name: '编辑 状态非法', method: 'PUT', path: `${B}/rows/2`, body: { status: 'bogus' }, auth: true },
  { name: '编辑 排序越界先于状态', method: 'PUT', path: `${B}/rows/2`, body: { status: 'bogus', sort_order: 2147483648 }, auth: true },
  { name: '编辑 空 body（无变化）', method: 'PUT', path: `${B}/rows/2`, body: {}, auth: true },
  {
    name: '编辑 同值（无变化）',
    method: 'PUT',
    path: `${B}/rows/2`,
    body: { row_code: 'ADV-002', score: '82', status: 'ARCHIVED', category: 'USER', progress: 'x', is_pinned: 'maybe', due_date: '2026-04-03' },
    auth: true,
  },
  { name: '编辑 score 舍入', method: 'PUT', path: `${B}/rows/2`, body: { score: 12.345, progress: 250, category: 'nope' }, auth: true, ignoreKeys: W },
  { name: '编辑 score 非法保持', method: 'PUT', path: `${B}/rows/2`, body: { score: 'abc', priority: '7' }, auth: true, ignoreKeys: W },
  { name: '编辑 score 溢出 → 500', method: 'PUT', path: `${B}/rows/2`, body: { score: 1e10 }, auth: true },
  {
    name: '编辑 恢复',
    method: 'PUT',
    path: `${B}/rows/2`,
    body: { score: 82, progress: 45, category: 'user', priority: 76 },
    auth: true,
    ignoreKeys: W,
  },
  { name: '删除 不存在', method: 'DELETE', path: `${B}/rows/99999999`, auth: true },
  // 排序
  { name: '排序 空对象', method: 'PUT', path: `${B}/rows/reorder`, body: {}, auth: true },
  { name: '排序 非数组', method: 'PUT', path: `${B}/rows/reorder`, body: { a: 1 }, auth: true },
  { name: '排序 元素非对象 → 500', method: 'PUT', path: `${B}/rows/reorder`, body: ['x'], auth: true },
  { name: '排序 越界 → 500', method: 'PUT', path: `${B}/rows/reorder`, body: [{ id: 0, sort_order: 99999999999 }], auth: true },
  {
    name: '排序 同值（无变化）',
    method: 'PUT',
    path: `${B}/rows/reorder`,
    body: [{ id: 2, sort_order: 20 }, { id: '3', sort_order: '10' }, { id: 99999999999, sort_order: 1 }, { sort_order: 5 }],
    auth: true,
  },
  // 批量
  { name: '批量更新 未选择', method: 'POST', path: `${B}/rows/batch-update`, body: {}, auth: true },
  { name: '批量更新 ids 非数组', method: 'POST', path: `${B}/rows/batch-update`, body: { ids: 'abc' }, auth: true },
  { name: '批量更新 未找到', method: 'POST', path: `${B}/rows/batch-update`, body: { ids: [99999999, null, 99999999999, 1.5] }, auth: true },
  { name: '批量更新 ids 非法字符串 → 500', method: 'POST', path: `${B}/rows/batch-update`, body: { ids: ['abc'] }, auth: true },
  { name: '批量更新 ids 布尔 → 500', method: 'POST', path: `${B}/rows/batch-update`, body: { ids: [true] }, auth: true },
  { name: '批量更新 状态非法 → 500', method: 'POST', path: `${B}/rows/batch-update`, body: { ids: [2], status: 'bogus' }, auth: true },
  {
    name: '批量更新 同值',
    method: 'POST',
    path: `${B}/rows/batch-update`,
    body: { ids: [2, '3', 2], status: '', is_active: 'maybe', priority: null },
    auth: true,
  },
  { name: '批量更新后统计不变', path: `${B}/stats`, auth: true },
  { name: '批量删除 未选择', method: 'POST', path: `${B}/rows/batch-delete`, body: { ids: [] }, auth: true },
  { name: '批量删除 未找到', method: 'POST', path: `${B}/rows/batch-delete`, body: { ids: [99999999] }, auth: true },
  { name: '批量删除 非法 → 500', method: 'POST', path: `${B}/rows/batch-delete`, body: { ids: [[1]] }, auth: true },
  { name: '最终列表', path: `${B}/rows?per_page=50`, auth: true },
]
