/**
 * Landing page copy per locale. Keys match the sections in Landing.vue.
 * The terminal script mirrors the real flow (autopilot → scaffold → migrate → seed:rbac → verify gate names).
 */

const SCAFFOLD = 'pnpm scaffold -- --name equipment --domain admin --fields "name:str,code:str50,status:str20,purchase_date:date,owner:str"'

export const CONTENT = {
  'zh-CN': {
    prefix: '',
    hero: {
      eyebrow: 'AI-First 全栈管理脚手架',
      title: ['描述需求，', '模块就绪。'],
      lead: 'castor-kit 把工程规范写成 AI 读得懂的上下文。数据表、接口、页面、权限、迁移，一句话生成完整功能模块，并由门禁自动验证后交付。',
      primary: '快速开始',
      secondary: 'GitHub',
      copy: '复制',
      copied: '已复制',
    },
    stats: [
      ['25+', '组件示例页面'],
      ['15', '项交付门禁检查'],
      ['3', '种界面语言'],
      ['1', '行命令部署'],
    ],
    showcase: {
      kicker: '开箱即用',
      title: '一个认真做过设计的管理后台',
      lead: '三种导航模式、六种强调色、浅色与深色、标签栏页面保活，都在「外观设置」里一键切换。下面这个界面就能点。',
      accent: '强调色',
      nav: '导航',
      navModes: { sidebar: '侧边栏', top: '顶部', mixed: '混合' },
      accents: { ocean: '海洋蓝', violet: '紫罗兰', emerald: '翡翠绿', rose: '玫瑰红', amber: '琥珀橙', slate: '石墨灰' },
      mock: {
        menu: ['首页', '用户管理', '角色权限', '菜单管理', '日志管理', '设备台账'],
        groups: ['首页', '组件示例', '系统管理'],
        title: '设备台账',
        search: '搜索设备名称',
        create: '新建设备',
        query: '查询',
        cols: ['名称', '编号', '状态', '负责人'],
        rows: [
          ['激光切割机', 'EQ-1024', '运行中', '王工'],
          ['数控车床', 'EQ-1025', '维护中', '李工'],
          ['三坐标测量仪', 'EQ-1031', '运行中', '陈工'],
          ['工业机器人', 'EQ-1042', '停用', '赵工'],
        ],
        status: { 运行中: 'ok', 维护中: 'warn', 停用: 'off' },
        tabs: ['首页', '用户管理', '设备台账'],
      },
    },
    ai: {
      kicker: 'AI 驱动开发',
      title: '从一句话，到可上线的模块',
      lead: 'AGENTS.md 是 AI 的唯一上下文：分层、命名、字段类型推断、权限、多语言规则都写在里面。Claude Code、Cursor、Copilot、Codex CLI 等工具读同一份规范，产出同一种代码。',
      points: [
        ['自动推断技术规格', '字段类型、表名、菜单与按钮权限由 AI 推断，你只确认业务预览。'],
        ['脚手架生成骨架', 'pnpm scaffold 一次生成后端四层、前端页面、接口测试与迁移。'],
        ['门禁把关交付', 'pnpm verify 跑类型检查、迁移链、路由注册、RBAC、前后端测试与构建。'],
      ],
      prompt: '做一个「设备台账」：名称、编号、状态、采购日期、负责人',
      script: [
        ['info', '推断规格　表 equipments · 5 个字段 · 菜单「设备台账」与按钮权限'],
        ['cmd', SCAFFOLD],
        ['ok', '生成 db/schema · schema · repository · service · routes · 页面 · 接口测试'],
        ['cmd', 'pnpm db:migrate'],
        ['ok', '已迁移至 0012_equipments'],
        ['cmd', 'pnpm seed:rbac -- --incremental'],
        ['ok', '菜单与按钮权限已同步'],
        ['cmd', 'pnpm verify -- --module equipment'],
        ['gate', 'typescript_compile · migration_chain · router_registration · rbac_sync · api_tests · frontend_tests · frontend_build'],
        ['done', '全部通过，交付完成'],
      ],
    },
    features: {
      kicker: '为什么是 castor-kit',
      title: '第一天就是生产级',
      items: [
        ['shield', '完整 RBAC', '用户、角色、菜单、按钮四层权限，新功能自动纳入权限体系，超级管理员一键放行。'],
        ['layers', '清晰分层', 'db/schema → schema → repository → service → routes，TypeScript strict + Zod 校验，第一千个功能和第一个一样整洁。'],
        ['languages', '三语国际化', '界面与接口报错支持中文、英文、日文，扫描与测试守卫防止漏翻。'],
        ['palette', '主题与布局', '六种强调色、三种导航模式、标签栏页面保活，所有颜色走语义 token。'],
        ['table', '导入导出', 'CSV / XLSX 导入导出组件与后端工具开箱即用，逐行校验并返回错误原因。'],
        ['container', '一行部署', 'bash setup.sh 完成数据库、服务、前端与 RBAC 初始化，Docker Compose 生产部署。'],
      ],
    },
    stack: { kicker: '技术栈' },
    cta: {
      title: '现在就开始',
      lead: '克隆仓库，运行安装向导，几分钟后就能登录后台。',
      primary: '阅读快速开始',
      secondary: '浏览组件示例',
    },
  },

  'en-US': {
    prefix: '/en',
    hero: {
      eyebrow: 'The AI-first full-stack admin scaffold',
      title: ['Describe it.', 'Ship the module.'],
      lead: 'castor-kit turns engineering conventions into context your AI can follow. Tables, APIs, pages, permissions and migrations: one sentence produces a complete feature module, verified by an automated gate before it ships.',
      primary: 'Get started',
      secondary: 'GitHub',
      copy: 'Copy',
      copied: 'Copied',
    },
    stats: [
      ['25+', 'example pages'],
      ['15', 'delivery gate checks'],
      ['3', 'UI languages'],
      ['1', 'command to deploy'],
    ],
    showcase: {
      kicker: 'Batteries included',
      title: 'An admin panel that was actually designed',
      lead: 'Three navigation modes, six accent colors, light and dark, a tabs bar that keeps pages alive — all one click away in the appearance menu. The panel below is interactive.',
      accent: 'Accent',
      nav: 'Navigation',
      navModes: { sidebar: 'Sidebar', top: 'Top', mixed: 'Mixed' },
      accents: { ocean: 'Ocean', violet: 'Violet', emerald: 'Emerald', rose: 'Rose', amber: 'Amber', slate: 'Slate' },
      mock: {
        menu: ['Home', 'Users', 'Roles', 'Menus', 'Logs', 'Equipment'],
        groups: ['Home', 'Gallery', 'System'],
        title: 'Equipment',
        search: 'Search equipment',
        create: 'New equipment',
        query: 'Search',
        cols: ['Name', 'Code', 'Status', 'Owner'],
        rows: [
          ['Laser cutter', 'EQ-1024', 'Running', 'Wang'],
          ['CNC lathe', 'EQ-1025', 'Maintenance', 'Li'],
          ['CMM probe', 'EQ-1031', 'Running', 'Chen'],
          ['Robot arm', 'EQ-1042', 'Retired', 'Zhao'],
        ],
        status: { Running: 'ok', Maintenance: 'warn', Retired: 'off' },
        tabs: ['Home', 'Users', 'Equipment'],
      },
    },
    ai: {
      kicker: 'AI-driven workflow',
      title: 'From one sentence to a shippable module',
      lead: 'AGENTS.md is the single source of context: layering, naming, field-type inference, permissions and i18n rules. Claude Code, Cursor, Copilot, Codex CLI and friends read the same rules and produce the same code.',
      points: [
        ['Specs inferred for you', 'Field types, table names, menus and button permissions are inferred; you only confirm a business preview.'],
        ['Scaffolded skeleton', 'pnpm scaffold generates all four backend layers, the page, API tests and the migration in one go.'],
        ['Gated delivery', 'pnpm verify runs type checks, the migration chain, route registration, RBAC, both test suites and the build.'],
      ],
      prompt: 'Build an "Equipment" registry: name, code, status, purchase date, owner',
      script: [
        ['info', 'Spec   table equipments · 5 fields · menu "Equipment" with button permissions'],
        ['cmd', SCAFFOLD],
        ['ok', 'Generated db/schema · schema · repository · service · routes · page · API tests'],
        ['cmd', 'pnpm db:migrate'],
        ['ok', 'Migrated to 0012_equipments'],
        ['cmd', 'pnpm seed:rbac -- --incremental'],
        ['ok', 'Menus and button permissions synced'],
        ['cmd', 'pnpm verify -- --module equipment'],
        ['gate', 'typescript_compile · migration_chain · router_registration · rbac_sync · api_tests · frontend_tests · frontend_build'],
        ['done', 'All checks passed, module delivered'],
      ],
    },
    features: {
      kicker: 'Why castor-kit',
      title: 'Production-grade from day one',
      items: [
        ['shield', 'Complete RBAC', 'Users, roles, menus and buttons; new features join the permission model automatically, super admins pass straight through.'],
        ['layers', 'Clear layering', 'db/schema → schema → repository → service → routes, strict TypeScript and Zod. Feature one thousand stays as clean as feature one.'],
        ['languages', 'Three languages', 'UI and API errors in Chinese, English and Japanese, with a scanner and tests that catch missing translations.'],
        ['palette', 'Theme & layout', 'Six accents, three nav modes and kept-alive tabs; every color goes through semantic tokens.'],
        ['table', 'Import & export', 'CSV / XLSX import and export on both ends, with row-level validation and error reasons.'],
        ['container', 'One-line deploy', 'bash setup.sh initializes the database, services, frontend and RBAC; Docker Compose in production.'],
      ],
    },
    stack: { kicker: 'Tech stack' },
    cta: {
      title: 'Start building',
      lead: 'Clone the repo, run the setup wizard, and sign in to your admin panel a few minutes later.',
      primary: 'Read the quick start',
      secondary: 'Browse the gallery',
    },
  },

  'ja-JP': {
    prefix: '/ja',
    hero: {
      eyebrow: 'AI ファーストのフルスタック管理スキャフォールド',
      title: ['要件を書けば、', 'モジュールが完成。'],
      lead: 'castor-kit はエンジニアリング規約を AI が理解できるコンテキストに変えます。テーブル、API、画面、権限、マイグレーションまで、一文から完全な機能モジュールを生成し、自動ゲートで検証してから届けます。',
      primary: 'はじめる',
      secondary: 'GitHub',
      copy: 'コピー',
      copied: 'コピーしました',
    },
    stats: [
      ['25+', 'サンプル画面'],
      ['15', '項目の納品ゲート'],
      ['3', 'つの UI 言語'],
      ['1', 'コマンドでデプロイ'],
    ],
    showcase: {
      kicker: 'すぐに使える',
      title: 'ちゃんとデザインされた管理画面',
      lead: '3 種類のナビゲーション、6 色のアクセント、ライトとダーク、ページ状態を保持するタブバー。すべて外観設定からワンクリックで切り替えられます。下の画面は実際に操作できます。',
      accent: 'アクセント',
      nav: 'ナビ',
      navModes: { sidebar: 'サイドバー', top: 'トップ', mixed: 'ミックス' },
      accents: { ocean: 'オーシャン', violet: 'バイオレット', emerald: 'エメラルド', rose: 'ローズ', amber: 'アンバー', slate: 'スレート' },
      mock: {
        menu: ['ホーム', 'ユーザー', 'ロール', 'メニュー', 'ログ', '設備台帳'],
        groups: ['ホーム', 'サンプル', 'システム'],
        title: '設備台帳',
        search: '設備名で検索',
        create: '設備を追加',
        query: '検索',
        cols: ['名称', 'コード', '状態', '担当者'],
        rows: [
          ['レーザー加工機', 'EQ-1024', '稼働中', '王'],
          ['NC 旋盤', 'EQ-1025', '保守中', '李'],
          ['三次元測定機', 'EQ-1031', '稼働中', '陳'],
          ['産業用ロボット', 'EQ-1042', '停止', '趙'],
        ],
        status: { 稼働中: 'ok', 保守中: 'warn', 停止: 'off' },
        tabs: ['ホーム', 'ユーザー', '設備台帳'],
      },
    },
    ai: {
      kicker: 'AI 駆動開発',
      title: '一文から、リリースできるモジュールへ',
      lead: 'AGENTS.md が AI の唯一のコンテキストです。レイヤー構成、命名、フィールド型の推論、権限、多言語のルールをすべて記述。Claude Code、Cursor、Copilot、Codex CLI などが同じ規約を読み、同じコードを書きます。',
      points: [
        ['仕様は自動推論', 'フィールド型、テーブル名、メニューとボタン権限は AI が推論。あなたは業務プレビューを確認するだけ。'],
        ['スキャフォールドで骨組み', 'pnpm scaffold がバックエンド 4 層、画面、API テスト、マイグレーションを一度に生成。'],
        ['ゲートで品質保証', 'pnpm verify が型チェック、マイグレーション、ルート登録、RBAC、テスト、ビルドを検証。'],
      ],
      prompt: '「設備台帳」を作って：名称、コード、状態、購入日、担当者',
      script: [
        ['info', '仕様推論　テーブル equipments · 5 フィールド · メニュー「設備台帳」とボタン権限'],
        ['cmd', SCAFFOLD],
        ['ok', 'db/schema · schema · repository · service · routes · 画面 · API テストを生成'],
        ['cmd', 'pnpm db:migrate'],
        ['ok', '0012_equipments まで適用'],
        ['cmd', 'pnpm seed:rbac -- --incremental'],
        ['ok', 'メニューとボタン権限を同期'],
        ['cmd', 'pnpm verify -- --module equipment'],
        ['gate', 'typescript_compile · migration_chain · router_registration · rbac_sync · api_tests · frontend_tests · frontend_build'],
        ['done', 'すべて合格、納品完了'],
      ],
    },
    features: {
      kicker: 'castor-kit を選ぶ理由',
      title: '初日から本番品質',
      items: [
        ['shield', '完全な RBAC', 'ユーザー・ロール・メニュー・ボタンの 4 層権限。新機能は自動で権限体系に組み込まれます。'],
        ['layers', '明快なレイヤー', 'db/schema → schema → repository → service → routes。strict な TypeScript と Zod で、千個目の機能も一個目と同じくきれい。'],
        ['languages', '3 言語対応', 'UI と API エラーを中国語・英語・日本語で。スキャナーとテストが翻訳漏れを防ぎます。'],
        ['palette', 'テーマとレイアウト', '6 色のアクセント、3 種類のナビ、状態を保持するタブ。色はすべてセマンティックトークン経由。'],
        ['table', 'インポート / エクスポート', 'CSV / XLSX の入出力をフロントとバックエンドで提供。行単位の検証とエラー理由付き。'],
        ['container', 'ワンライナーでデプロイ', 'bash setup.sh でデータベース、サービス、フロントエンド、RBAC を初期化。本番は Docker Compose。'],
      ],
    },
    stack: { kicker: '技術スタック' },
    cta: {
      title: 'さっそく始めよう',
      lead: 'リポジトリをクローンしてセットアップウィザードを実行すれば、数分後には管理画面にログインできます。',
      primary: 'クイックスタートを読む',
      secondary: 'サンプルを見る',
    },
  },
}

export const STACK = ['Node.js 22', 'TypeScript', 'Fastify 5', 'Drizzle ORM', 'PostgreSQL', 'Zod', 'React 19', 'shadcn/ui', 'Tailwind CSS v4', 'Motion', 'i18next', 'Vite', 'Vitest', 'Docker', 'MCP']

export const INSTALL = 'git clone https://github.com/robeshell/castor-kit.git && cd castor-kit && bash setup.sh'
