/**
 * Standard list page template (shadcn/ui stack, with import/export)
 *
 * Replacement notes:
 *   - <Resource> → PascalCase resource name (e.g. CustomerOrder); <resource> → snake_case (e.g. customer_order)
 *   - <module> → admin or component_center (same as the module the page lives in)
 *   - Fill in the real fields: EXPORT_FIELDS (keys match the backend EXPORT_FIELD_MAP), EMPTY_VALUES / toFormValues, columns, form fields
 *   - Field type → form component: str→FormInput, text→FormTextarea, int/float→FormNumber, bool→FormSwitch,
 *     date→FormDate, datetime→FormDateTime; enum→FormSelect (options [{label,value}])
 *   - Table columns: bool/status → StatusBadge; dates → formatDate / formatDateTime; numbers get tabular-nums
 *
 * Reference implementation: apps/web/src/modules/admin/pages/users/index.jsx; pages generated by `pnpm scaffold` are instances of this template.
 * Design and conventions: docs/frontend-redesign-plan.md
 */
import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { AnimatePresence, motion } from 'motion/react'
import { Download, Plus, Upload, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { formatDateTime } from '@/lib/format'
import { toast } from '@/lib/toast'
import {
  createItem,
  deleteItem,
  downloadTemplate,
  exportItems,
  getItems,
  importItems,
  updateItem,
} from '@/modules/<module>/api/<resource>'
import ConfirmAction from '@/shared/components/ConfirmAction'
import DataTable from '@/shared/components/DataTable'
import ExportDialog from '@/shared/components/data-transfer/ExportDialog'
import ImportDialog from '@/shared/components/data-transfer/ImportDialog'
import { FilterBar, FilterSelect, SearchInput } from '@/shared/components/Filters'
import { FormDialog } from '@/shared/components/FormDialog'
import { FormInput, FormSelect, FormTextarea } from '@/shared/components/FormFields'
import PageHeader from '@/shared/components/PageHeader'
import StatusBadge from '@/shared/components/StatusBadge'
import { useCrudList } from '@/shared/hooks/useCrudList'
import { downloadBlobFile } from '@/shared/utils/file'

// Adjust to the real fields (keys match the backend EXPORT_FIELD_MAP)
const EXPORT_FIELDS = [
  { label: 'ID', value: 'id' },
  { label: '名称', value: 'name' },
  { label: '状态', value: 'status' },
  { label: '创建时间', value: 'created_at' },
]

// Enum: shared by the filter and the form; tone determines the StatusBadge color
const STATUS_OPTIONS = [
  { label: '启用', value: 'active', tone: 'success' },
  { label: '停用', value: 'inactive', tone: 'neutral' },
]
const STATUS_MAP = Object.fromEntries(STATUS_OPTIONS.map((o) => [o.value, o]))

const normalizeFileType = (raw) => (['csv', 'xlsx'].includes(raw) ? raw : 'xlsx')

const EMPTY_VALUES = { name: '', status: 'active', remark: '' }

/** Edit: take only form fields (id / created_at are not sent back); convert dates to picker format with formatDate(v, '') / formatDateTime(v, '') */
const toFormValues = (record) => ({
  name: record.name ?? '',
  status: record.status ?? 'active',
  remark: record.remark ?? '',
})

export default function <Resource>Page() {
  const list = useCrudList(
    (params) =>
      getItems(params).catch((err) => {
        toast.apiError(err, '加载失败')
        return { items: [], total: 0 }
      }),
    { defaultPerPage: 20 },
  )
  const { data, total, loading, page, perPage, filters, fetchData, handlePageChange } = list
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [selectedKeys, setSelectedKeys] = useState([])
  const [editing, setEditing] = useState(null)
  const [formOpen, setFormOpen] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  const [importOpen, setImportOpen] = useState(false)

  const form = useForm({ defaultValues: EMPTY_VALUES })

  useEffect(() => {
    fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- fetch only once on mount
  }, [])

  // ── Create / Edit ───────────────────────────────────────────────────────────
  const openCreate = () => {
    setEditing(null)
    form.reset(EMPTY_VALUES)
    setFormOpen(true)
  }

  const openEdit = (record) => {
    setEditing(record)
    form.reset(toFormValues(record))
    setFormOpen(true)
  }

  // On throw, FormDialog stays open; the backend {error} message is shown by toast.apiError
  const submit = async (values) => {
    try {
      if (editing) {
        await updateItem(editing.id, values)
        toast.success('更新成功')
      } else {
        await createItem(values)
        toast.success('创建成功')
      }
      setFormOpen(false)
      fetchData()
    } catch (err) {
      toast.apiError(err, '操作失败')
      throw err
    }
  }

  // ── Delete ──────────────────────────────────────────────────────────────────
  const remove = async (record) => {
    try {
      await deleteItem(record.id)
      toast.success('删除成功')
      setSelectedKeys((keys) => keys.filter((k) => k !== record.id))
      fetchData()
    } catch (err) {
      toast.apiError(err, '删除失败')
      throw err
    }
  }

  // ── Filters ─────────────────────────────────────────────────────────────────
  const runSearch = () => {
    setSelectedKeys([])
    list.handleSearch({ search: search.trim(), status })
  }
  const reset = () => {
    setSearch('')
    setStatus('')
    setSelectedKeys([])
    list.handleReset()
  }

  // ── Export: selection takes priority (ids); if the backend supports filtered export, add payload.filters = filters here ─────
  const handleExport = async ({ fields, fileType }) => {
    const type = normalizeFileType(fileType)
    const payload = { fields, file_type: type }
    if (selectedKeys.length) payload.ids = selectedKeys
    try {
      const blob = await exportItems(payload)
      downloadBlobFile(blob, `<resource>_export.${type}`)
      toast.success('导出成功')
      setExportOpen(false)
    } catch (err) {
      toast.apiError(err, '导出失败')
    }
  }

  // ── Table columns ───────────────────────────────────────────────────────────
  const columns = [
    { key: 'id', title: 'ID', dataIndex: 'id', width: 72, className: 'text-muted-foreground tabular-nums' },
    { key: 'name', title: '名称', dataIndex: 'name', render: (value) => <span className="font-medium">{value}</span> },
    {
      key: 'status',
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (value) => (
        <StatusBadge tone={STATUS_MAP[value]?.tone ?? 'neutral'} dot>
          {STATUS_MAP[value]?.label ?? value ?? '-'}
        </StatusBadge>
      ),
    },
    {
      key: 'created_at',
      title: '创建时间',
      dataIndex: 'created_at',
      width: 180,
      className: 'text-muted-foreground tabular-nums',
      render: (value) => formatDateTime(value),
    },
    {
      key: 'actions',
      title: '',
      align: 'right',
      width: 132,
      render: (_, record) => (
        <div className="flex justify-end gap-0.5">
          <Button variant="ghost" size="sm" className="h-7 px-2" onClick={() => openEdit(record)}>
            编辑
          </Button>
          <ConfirmAction title={`删除「${record.name}」？`} description="删除后不可恢复。" confirmText="删除" onConfirm={() => remove(record)}>
            <Button variant="ghost" size="sm" className="text-danger hover:text-danger h-7 px-2">
              删除
            </Button>
          </ConfirmAction>
        </div>
      ),
    },
  ]

  return (
    <div>
      {/* Page header: at most one variant="brand" primary action per page; the rest are outline / ghost */}
      <PageHeader
        title="<页面标题>"
        actions={
          <>
            <Button variant="outline" size="sm" onClick={() => setImportOpen(true)}>
              <Upload />
              导入
            </Button>
            <Button variant="outline" size="sm" onClick={() => setExportOpen(true)}>
              <Download />
              导出
            </Button>
            <Button size="sm" variant="brand" onClick={openCreate}>
              <Plus />
              新增
            </Button>
          </>
        }
      />

      {/* Filter bar */}
      <FilterBar onSearch={runSearch} onReset={reset}>
        <SearchInput value={search} onChange={setSearch} onSubmit={runSearch} placeholder="搜索名称" />
        <FilterSelect value={status} onChange={setStatus} options={STATUS_OPTIONS} placeholder="全部状态" />
      </FilterBar>

      {/* Selection banner */}
      <AnimatePresence>
        {selectedKeys.length > 0 ? (
          <motion.div
            initial={{ opacity: 0, y: -6, height: 0 }}
            animate={{ opacity: 1, y: 0, height: 'auto' }}
            exit={{ opacity: 0, y: -6, height: 0 }}
            className="overflow-hidden"
          >
            <div className="bg-brand-soft mb-3 flex items-center gap-3 rounded-lg px-3 py-2 text-[13px]">
              <span>
                已勾选 <span className="font-medium tabular-nums">{selectedKeys.length}</span> 条，导出时将优先导出勾选数据
              </span>
              <Button variant="ghost" size="sm" className="ml-auto h-7" onClick={() => setSelectedKeys([])}>
                <X />
                清空勾选
              </Button>
            </div>
          </motion.div>
        ) : null}
      </AnimatePresence>

      {/* Table: loading skeleton, empty state and pagination are provided by DataTable */}
      <DataTable
        columns={columns}
        data={data}
        loading={loading}
        selectable
        selectedKeys={selectedKeys}
        onSelectionChange={setSelectedKeys}
        pagination={{ page, perPage, total, onChange: handlePageChange }}
        emptyTitle="暂无数据"
        emptyDescription={filters.search || filters.status ? '换个筛选条件试试' : '点击右上角「新增」添加第一条数据'}
      />

      {/* Create / Edit (react-hook-form); write rules' messages following backend/product copy */}
      <FormDialog open={formOpen} onOpenChange={setFormOpen} title={editing ? '编辑' : '新增'} form={form} onSubmit={submit}>
        <FormInput control={form.control} name="name" label="名称" placeholder="请输入名称" rules={{ required: '请输入名称' }} />
        <FormSelect control={form.control} name="status" label="状态" options={STATUS_OPTIONS} />
        <FormTextarea control={form.control} name="remark" label="备注" placeholder="选填" />
      </FormDialog>

      <ExportDialog
        open={exportOpen}
        onOpenChange={setExportOpen}
        title="导出<资源名>"
        ruleHint={selectedKeys.length ? `已勾选 ${selectedKeys.length} 条，将只导出勾选数据。` : '未勾选数据时导出全部数据。'}
        fieldOptions={EXPORT_FIELDS}
        onConfirm={handleExport}
      />

      <ImportDialog
        open={importOpen}
        onOpenChange={setImportOpen}
        title="导入<资源名>"
        targetLabel="<资源名>"
        onDownloadTemplate={(fileType) =>
          downloadTemplate(normalizeFileType(fileType))
            .then((blob) => {
              downloadBlobFile(blob, `<resource>_import_template.${normalizeFileType(fileType)}`)
              toast.success('模板已下载')
            })
            .catch((err) => toast.apiError(err, '模板下载失败'))
        }
        onImport={(file) => importItems(file)}
        onImported={(res) => {
          toast.success(`导入成功：新增 ${res?.created || 0} 条，更新 ${res?.updated || 0} 条`)
          fetchData()
        }}
        errorExportFileName="<resource>_import_error_rows.csv"
      />
    </div>
  )
}
