/**
 * Removing a generated module again (the visual modeler's undo, and the rollback of a failed generation).
 *
 * Shared files are edited line by line instead of being restored from a backup, so modules generated later — and
 * anything else changed since — stay intact. Each transform returns the new content, or null when there is nothing
 * of the module left in it.
 */

import type { GeneratedModule } from '../../src/modules/admin/modeler/files'
import { BIZ_GROUP } from './menus'

const escape = (text: string) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

function dropLines(content: string, drop: (line: string) => boolean): string | null {
  const lines = content.split('\n')
  const kept = lines.filter((line) => !drop(line))
  return kept.length === lines.length ? null : kept.join('\n')
}

/** db/schema/index.ts: the `export * from './<domainDir>/<kebab>'` line */
export function unregisterSchema(content: string, m: Pick<GeneratedModule, 'domainDir' | 'kebab'>): string | null {
  const re = new RegExp(`^export \\* from ['"]\\./${escape(`${m.domainDir}/${m.kebab}`)}['"];?\\s*$`)
  return dropLines(content, (line) => re.test(line))
}

/** modules/<domain>/router.ts: the import and the `await register<Name>Routes(app)` call */
export function unregisterRoute(content: string, m: Pick<GeneratedModule, 'pascal'>): string | null {
  const fn = `register${m.pascal}Routes`
  const re = new RegExp(`\\b${escape(fn)}\\b`)
  return dropLines(content, (line) => re.test(line))
}

/** Permission codes of a module: the menu and its buttons */
export function moduleCodes(permPrefix: string): string[] {
  return [permPrefix, ...['_add', '_edit', '_delete', '_export', '_import'].map((s) => `${permPrefix}${s}`)]
}

/** scripts/seed-rbac.ts: the module's menu / button lines and the comment above them */
export function unregisterMenus(content: string, m: Pick<GeneratedModule, 'permPrefix' | 'pascal'>): string | null {
  const codes = new Set(moduleCodes(m.permPrefix))
  const comment = `// ${m.pascal} (generated by scripts/scaffold.ts)`
  return dropLines(content, (line) => {
    if (line.trim() === comment) return true
    const code = /\bcode:\s*"([^"]+)"/.exec(line)?.[1]
    return code !== undefined && codes.has(code)
  })
}

/** apps/web/src/locales/menus/<lang>.json: the module's menu names */
export function removeMenuNames(content: string, m: Pick<GeneratedModule, 'permPrefix'>): string | null {
  const names = JSON.parse(content) as Record<string, string>
  const codes = moduleCodes(m.permPrefix).filter((code) => code in names)
  if (codes.length === 0) return null
  for (const code of codes) delete names[code]
  return `${JSON.stringify(names, null, 2)}\n`
}

/** docs/apifox-full.openapi.json: the module's paths */
export function removeApiPaths(content: string, m: Pick<GeneratedModule, 'apiBase'>): string | null {
  const doc = JSON.parse(content) as { paths?: Record<string, unknown> }
  const paths = Object.keys(doc.paths ?? {}).filter((p) => p === m.apiBase || p.startsWith(`${m.apiBase}/`))
  if (paths.length === 0) return null
  for (const path of paths) delete doc.paths![path]
  // The generator writes the document without a trailing newline
  return JSON.stringify(doc, null, 2)
}

interface Journal {
  entries: Array<{ idx: number; tag: string; when: number }>
}

/** drizzle/meta/_journal.json: the module's migration entry (only when it is the last one — the chain must stay intact) */
export function removeJournalEntry(content: string, tag: string): string | null {
  const journal = JSON.parse(content) as Journal
  const last = journal.entries.at(-1)
  if (!journal.entries.some((e) => e.tag === tag)) return null
  if (last?.tag !== tag) throw new Error(`迁移 ${tag} 之后还有其他迁移，不能自动撤销；请手动处理后再删除模块`)
  journal.entries.pop()
  return `${JSON.stringify(journal, null, 2)}`
}

/** The journal's last entry (the migration a generation just added is the new last one) */
export function lastJournalEntry(content: string): { tag: string; when: number } | null {
  const last = (JSON.parse(content) as Journal).entries.at(-1)
  return last ? { tag: last.tag, when: last.when } : null
}

/** seed-rbac.ts without the business group when no menu hangs under it any more; null when it stays (or isn't there) */
export function dropEmptyBizGroup(content: string): string | null {
  const group = content.split('\n').find((line) => new RegExp(`\\bcode:\\s*"${BIZ_GROUP.code}"`).test(line))
  const id = group ? /\bid:\s*(\d+)/.exec(group)?.[1] : undefined
  if (!group || !id) return null
  if (new RegExp(`\\bparent_id:\\s*${id}\\b`).test(content)) return null
  return dropLines(content, (line) => line === group)
}

/** Menu locales without the business group's name */
export function removeGroupName(content: string): string | null {
  const names = JSON.parse(content) as Record<string, string>
  if (!(BIZ_GROUP.code in names)) return null
  delete names[BIZ_GROUP.code]
  return `${JSON.stringify(names, null, 2)}\n`
}
