#!/bin/bash
# Castor one-step installer
# Usage: bash scripts/setup.sh (from any directory)

set -e

# Work from the repository root: .env.production and docker-compose.yml live there
cd "$(dirname "$0")/.."

# ── Colors ────────────────────────────────────────────────────
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
RED=$'\033[0;31m'
BOLD=$'\033[1m'
NC=$'\033[0m'

info()    { echo "${GREEN}✓${NC} $1"; }
warn()    { echo "${YELLOW}!${NC} $1"; }
error()   { printf '%b\n' "${RED}✗ Error: $1${NC}"; exit 1; }
heading() { echo ""; echo "${BOLD}$1${NC}"; }

# ── Welcome ───────────────────────────────────────────────────
clear 2>/dev/null || true
echo "${BOLD}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║             Castor setup             ║"
echo "  ╚══════════════════════════════════════╝"
echo "${NC}"
echo "  This script configures everything and starts the app."
echo "  It takes about 3-5 minutes, depending on your network speed."
echo ""

# ── Check Docker ──────────────────────────────────────────────
heading "Step 1: Check the environment"

if ! command -v docker &>/dev/null; then
    error "Docker was not found.\n\n  Install Docker Desktop first:\n  https://www.docker.com/products/docker-desktop/\n\n  Then run this script again."
fi

if ! docker info &>/dev/null 2>&1; then
    error "Docker is not running.\n\n  Open Docker Desktop, wait until it has fully started, then run this script again."
fi

if ! docker compose version &>/dev/null 2>&1; then
    error "The docker compose plugin was not found.\n\n  Update Docker Desktop to the latest version."
fi

info "Docker is ready"

# ── Configuration ─────────────────────────────────────────────
heading "Step 2: Create the configuration"

# If a config already exists, ask whether to reconfigure
if [ -f ".env.production" ]; then
    echo ""
    read -p "  A configuration file already exists. Reconfigure? [y/N] " RECONFIG
    RECONFIG=${RECONFIG:-N}
    if [[ ! "$RECONFIG" =~ ^[Yy]$ ]]; then
        info "Keeping the existing configuration; skipping this step"
        SKIP_CONFIG=true
    fi
fi

if [ -z "$SKIP_CONFIG" ]; then
    echo ""
    echo "  Set the admin password (press Enter to use the default, admin123)."
    read -s -p "  Admin password: " ADMIN_PASSWORD
    echo ""
    ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}

    # Ask for the port
    echo ""
    echo "  Set the port (press Enter to use the default, 5000)."
    read -p "  Port: " APP_PORT
    APP_PORT=${APP_PORT:-5000}

    # Ask about AI features
    echo ""
    echo "  Configure the AI features (AI Chat, AI Prompt Studio) now?"
    echo "  You can skip this and configure them after signing in, under System settings → AI (values entered here are locked as read-only)."
    read -p "  Configure AI now? [y/N] " SETUP_AI
    SETUP_AI=${SETUP_AI:-N}

    AI_API_KEY=""
    AI_API_BASE=""
    AI_MODEL=""
    if [[ "$SETUP_AI" =~ ^[Yy]$ ]]; then
        echo ""
        echo "  Any OpenAI-compatible API works (OpenAI, Claude, and others)."
        read -p "  API key: " AI_API_KEY
        read -p "  API base URL: " AI_API_BASE
        read -p "  Model name (e.g. gpt-4o): " AI_MODEL
    fi

    # Generate a random SECRET_KEY and read-only account password
    SECRET_KEY=$(LC_ALL=C tr -dc 'A-Za-z0-9!@#$%^&*' < /dev/urandom | head -c 64 2>/dev/null || openssl rand -base64 48)
    POSTGRES_RO_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 24 2>/dev/null || openssl rand -base64 18)

    # Write the config file
    cat > .env.production <<EOF
# Castor production configuration
# Generated by scripts/setup.sh. Do not change SECRET_KEY by hand.

NODE_ENV=production
SECRET_KEY=${SECRET_KEY}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
APP_PORT=${APP_PORT}
POSTGRES_PASSWORD=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 24 2>/dev/null || openssl rand -base64 18)
POSTGRES_RO_PASSWORD=${POSTGRES_RO_PASSWORD}

# AI features (optional)
AI_API_KEY=${AI_API_KEY}
AI_API_BASE=${AI_API_BASE}
AI_MODEL=${AI_MODEL}
EOF

    info "Configuration written to .env.production"
fi

# Load the config
set -a
# shellcheck disable=SC1091
source .env.production
set +a
APP_PORT=${APP_PORT:-5000}

# ── Configure registry mirrors (if daemon.json has none) ─────────
configure_mirrors() {
    if [[ "$OSTYPE" == "darwin"* ]]; then
        local cfg="$HOME/.docker/daemon.json"
    else
        local cfg="/etc/docker/daemon.json"
    fi

    # Skip if already configured
    if [[ -f "$cfg" ]] && grep -q "registry-mirrors" "$cfg" 2>/dev/null; then
        return 0
    fi

    echo "  Configuring a Docker registry mirror..."
    local mirrors='["https://docker.xuanyuan.me"]'
    mkdir -p "$(dirname "$cfg")"

    local compact
    compact="$(tr -d ' \t\r\n' 2>/dev/null < "$cfg" || true)"
    if [[ -z "$compact" || "$compact" == "{}" ]]; then
        echo "{\"registry-mirrors\": $mirrors}" > "$cfg"
    elif command -v node &>/dev/null; then
        # Merge into the existing config
        CFG="$cfg" MIRRORS="$mirrors" node -e '
const fs = require("fs")
const file = process.env.CFG
const config = JSON.parse(fs.readFileSync(file, "utf8"))
config["registry-mirrors"] = JSON.parse(process.env.MIRRORS)
fs.writeFileSync(file, JSON.stringify(config, null, 2) + "\n")
' 2>/dev/null || echo "{\"registry-mirrors\": $mirrors}" > "$cfg"
    else
        # No node: add the key right after the opening brace of the existing object
        awk -v entry="\"registry-mirrors\": $mirrors," '!done && sub(/\{/, "{" entry) { done = 1 } { print }' "$cfg" > "$cfg.tmp" && mv "$cfg.tmp" "$cfg"
    fi

    # Restart Docker to apply the config
    if [[ "$OSTYPE" == "darwin"* ]]; then
        osascript -e 'quit app "Docker"' 2>/dev/null || true
        sleep 2
        open -a Docker 2>/dev/null || true
        printf "  Waiting for Docker to restart"
        for i in $(seq 1 30); do
            docker info &>/dev/null 2>&1 && break
            printf "."; sleep 2
        done
        echo ""
    else
        sudo systemctl restart docker 2>/dev/null || true
    fi
    info "Registry mirror configured (docker.xuanyuan.me)"
}

configure_mirrors

# ── Start ─────────────────────────────────────────────────────
heading "Step 3: Build and start the app"
echo ""
echo "  Building the image and starting the services..."
echo "  (The first run downloads dependencies and takes about 3-5 minutes.)"
echo ""

docker compose --env-file .env.production up -d --build

# ── Wait for health check ──────────────────────────────────────
heading "Step 4: Wait for the app to be ready"

echo ""
printf "  Waiting for the app to start"
for i in $(seq 1 30); do
    if curl -sf "http://localhost:${APP_PORT}/health" &>/dev/null; then
        echo ""
        break
    fi
    printf "."
    sleep 3
done
echo ""

if ! curl -sf "http://localhost:${APP_PORT}/health" &>/dev/null; then
    warn "The app is not responding yet; it may need more time to start."
    warn "To view the logs, run: docker compose --env-file .env.production logs -f app"
else
    info "The app is ready"
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "${BOLD}${GREEN}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║           Setup complete!            ║"
echo "  ╚══════════════════════════════════════╝"
echo "${NC}"
echo "  URL:       ${BOLD}http://localhost:${APP_PORT}${NC}"
echo "  Username:  ${BOLD}admin${NC}"
echo "  Password:  ${BOLD}${ADMIN_PASSWORD}${NC}"
echo ""
echo "  Common commands:"
echo "    Stop:       docker compose --env-file .env.production down"
echo "    View logs:  docker compose --env-file .env.production logs -f app"
echo "    Restart:    docker compose --env-file .env.production up -d"
echo ""
