/**
 * scripts/lib/modeler-undo.ts: removing a generated module gives back the shared files exactly as they were,
 * and leaves other modules alone (round trips against the repo's real files)
 */

import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { insertMenus, menuNames, planMenus } from '../scripts/lib/menus'
import {
  lastJournalEntry,
  removeApiPaths,
  removeJournalEntry,
  removeMenuNames,
  unregisterMenus,
  unregisterRoute,
  unregisterSchema,
} from '../scripts/lib/modeler-undo'
import { buildSpec, registerRoute, registerSchemaExport } from '../scripts/scaffold'

const API_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const REPO_ROOT = resolve(API_DIR, '..', '..')
const read = (rel: string) => readFileSync(join(REPO_ROOT, rel), 'utf8')

const a = buildSpec('ck_undo_a', 'admin', [['name', 'str']], { title: '甲' })
const b = buildSpec('ck_undo_b', 'admin', [['name', 'str']], { title: '乙' })
const moduleOf = (s: typeof a) => ({ ...s, apiBase: s.apiBase })
const request = (s: typeof a) => ({
  title: s.title,
  titles: { 'en-US': 'A', 'ja-JP': 'A' },
  permPrefix: s.permPrefix,
  component: s.menuComponent,
  path: `/biz/${s.kebab}s`,
})

describe('modeler undo', () => {
  it('db/schema/index.ts 与 router.ts：注册后撤销还原原文，只去掉这一个模块', () => {
    const index = read('apps/api/src/db/schema/index.ts')
    const both = registerSchemaExport(registerSchemaExport(index, 'admin', a.kebab)!, 'admin', b.kebab)!
    expect(unregisterSchema(unregisterSchema(both, a)!, b)).toBe(index)
    expect(unregisterSchema(both, a)).toContain(`export * from './admin/${b.kebab}'`)
    expect(unregisterSchema(index, a)).toBeNull()

    const router = read('apps/api/src/modules/admin/router.ts')
    const routed = registerRoute(registerRoute(router, a.pascal, a.kebab)!, b.pascal, b.kebab)!
    expect(unregisterRoute(unregisterRoute(routed, a)!, b)).toBe(router)
    expect(unregisterRoute(routed, a)).toContain(`register${b.pascal}Routes`)
  })

  it('seed-rbac.ts 与菜单译文：撤销一个模块不影响另一个，都撤销后还原原文', () => {
    const seed = read('apps/api/scripts/seed-rbac.ts')
    const ea = planMenus(seed, request(a))!
    const withA = insertMenus(seed, ea, `${a.pascal} (generated by scripts/scaffold.ts)`)
    const eb = planMenus(withA, request(b))!
    const withBoth = insertMenus(withA, eb, `${b.pascal} (generated by scripts/scaffold.ts)`)
    const onlyB = unregisterMenus(withBoth, moduleOf(a))!
    expect(onlyB).not.toContain(a.permPrefix)
    expect(onlyB).toContain(`code: "${b.permPrefix}_import"`)
    // The group added with the first module stays (other modules may use it)
    const cleared = unregisterMenus(onlyB, moduleOf(b))!
    const groupLine = ea.find((e) => e.code === 'biz') ? /\n {2}\{ id: \d+, name: "业务管理", code: "biz"[^\n]*/ : null
    expect(groupLine ? cleared.replace(groupLine, '').replace(/\n {2}\/\/ CkUndoA \(generated by scripts\/scaffold\.ts\)/, '') : cleared).toBe(seed)

    const names = read('apps/web/src/locales/menus/en-US.json')
    const withNames = `${JSON.stringify({ ...JSON.parse(names), ...menuNames(ea, request(a), 'en-US') }, null, 2)}\n`
    expect(JSON.parse(removeMenuNames(withNames, moduleOf(a))!)).toEqual({
      ...JSON.parse(names),
      ...(ea.some((e) => e.code === 'biz') ? { biz: 'Business' } : {}),
    })
  })

  it('OpenAPI 与迁移日志：去掉这个模块的路径；只有最后一个迁移才能撤销', () => {
    const doc = JSON.stringify({ paths: { '/api/admin/ck-undo-as': {}, '/api/admin/ck-undo-as/{item_id}': {}, '/api/admin/ck-undo-asx': {} } }, null, 2)
    expect(Object.keys(JSON.parse(removeApiPaths(doc, a)!).paths)).toEqual(['/api/admin/ck-undo-asx'])
    expect(removeApiPaths(JSON.stringify({ paths: {} }), a)).toBeNull()

    const journal = read('apps/api/drizzle/meta/_journal.json')
    const parsed = JSON.parse(journal) as { entries: Array<{ idx: number; tag: string; when: number }> }
    const added = JSON.stringify({ ...parsed, entries: [...parsed.entries, { idx: 99, version: '7', when: 1, tag: '0099_ck_undo_a', breakpoints: true }] }, null, 2)
    expect(lastJournalEntry(added)).toEqual({ tag: '0099_ck_undo_a', when: 1 })
    expect(removeJournalEntry(added, '0099_ck_undo_a')).toBe(journal)
    const first = parsed.entries[0]!.tag
    expect(() => removeJournalEntry(journal, first)).toThrow('之后还有其他迁移')
    expect(removeJournalEntry(journal, '0099_missing')).toBeNull()
  })
})
